version: '3.3'

services:
    api:
        container_name: 'api'
        build: "./"
        ports:
            - '8080:8080'
        volumes: 
            - './api:/api'
        depends_on: 
            - 'mongo'
    mongo:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports: 
            - '27017:27017'